### ISSUE TITLE
Add todo

### ISSUE THREAD

**Issue by lukwys** [sylwesterdz/todo-app-vanilla#5]
- [x]  add input element where user can add todo
- [x] add button (send a request with todo title after mouse click and press enter key) 
- [x] refresh todos list
